In [28]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns

In [29]:
year = 2024

In [30]:
savor = pd.read_csv('Statement-SavorOne2024.csv', encoding='unicode_escape')
venture = pd.read_csv('Statement-VentureOne2024.csv', encoding='unicode_escape')
combined = pd.concat([savor, venture])
savor.head()

,Transaction Date,Posted Date,Card No.,Description,Category,Debit,Credit
0,12/31/2024,12/31/2024,9828,D J*WSJ,Other Services,4.36,NaN
1,12/30/2024,12/31/2024,9828,WL *STEAM PURCHASE,Internet,21.76,NaN
2,12/30/2024,12/31/2024,9828,Spectrum,Phone/Cable,56.99,NaN
3,12/28/2024,12/30/2024,9828,4223 ZAROS BAKERY,Dining,6.15,NaN
4,12/27/2024,12/28/2024,9828,DUANE READE #14169,Health Care,8.67,NaN

In [31]:
venture.head()

,Transaction Date,Posted Date,Card No.,Description,Category,Debit,Credit
0,2024-12-30,2024-12-30,7050,SOUVLAKI FAST ONLINE,Internet,53.71,NaN
1,2024-12-27,2024-12-30,7050,SMOKE ZONE,Merchandise,44.23,NaN
2,2024-12-28,2024-12-30,7050,LYFT *3 RIDES 12-27,Other Travel,4.71,NaN
3,2024-12-27,2024-12-30,7050,TST*7TH STREET BURGER -,Dining,20.62,NaN
4,2024-12-27,2024-12-28,7050,MORTON WILLIAMS - G,Merchandise,23.24,NaN

In [41]:
combined.head()

,Transaction Date,Posted Date,Card No.,Description,Category,Debit,Credit
0,2024-12-31,2024-12-31,9828,D J*WSJ,Other Services,4.36,NaN
1,2024-12-30,2024-12-31,9828,WL *STEAM PURCHASE,Internet,21.76,NaN
2,2024-12-30,2024-12-31,9828,Spectrum,Phone/Cable,56.99,NaN
3,2024-12-28,2024-12-30,9828,4223 ZAROS BAKERY,Dining,6.15,NaN
4,2024-12-27,2024-12-28,9828,DUANE READE #14169,Health Care,8.67,NaN

In [42]:
combined.tail()

,Transaction Date,Posted Date,Card No.,Description,Category,Debit,Credit
1271,2023-12-31,2024-01-02,7050,UBER TRIP,Other Travel,5.00,NaN
1272,2023-12-31,2024-01-02,7050,UBER TRIP,Other Travel,19.90,NaN
1273,2023-12-29,2024-01-02,7050,4033 ZAROS BAKERY,Dining,17.97,NaN
1274,2023-12-31,2024-01-02,7050,TST* JOES PIZZA - MIAMI,Dining,22.23,NaN
1275,2023-12-31,2024-01-02,7050,WALGREENS #2790,Health Care,34.83,NaN

In [43]:
print('This dataset has', combined.shape[1], 'columns and', combined.shape[0], 'rows')
print('\n')
print(combined.info())

This dataset has 7 columns and 1975 rows


<class 'pandas.core.frame.DataFrame'>
Int64Index: 1975 entries, 0 to 1275
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction Date  1975 non-null   datetime64[ns]
 1   Posted Date       1975 non-null   datetime64[ns]
 2   Card No.          1975 non-null   int64
 3   Description       1975 non-null   object
 4   Category          1975 non-null   object
 5   Debit             1948 non-null   float64
 6   Credit            27 non-null     float64
dtypes: datetime64[ns](2), float64(2), int64(1), object(2)
memory usage: 123.4+ KB
None

In [45]:
combined['Transaction Date'] = pd.to_datetime(combined['Transaction Date'])
combined['Posted Date'] = pd.to_datetime(combined['Posted Date'])
combined.describe(include='all').T

C:\Users\TYLEVY~1\AppData\Local\Temp/ipykernel_20952/3873869570.py:3: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  combined.describe(include='all').T

,count,unique,top,freq,first,last,mean,std,min,25%,50%,75%,max
Transaction Date,1975,363,2024-05-24 00:00:00,12,2023-12-29,2024-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Posted Date,1975,310,2024-10-07 00:00:00,17,2024-01-02,2024-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Card No.,1975.0,NaN,NaN,NaN,NaT,NaT,8033.201013,1328.737042,7050.0,7050.0,7050.0,9828.0,9828.0
Description,1975,697,MTA*NYCT PAYGO,215,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Category,1975,15,Dining,756,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Debit,1948.0,NaN,NaN,NaN,NaT,NaT,17.347433,29.369184,0.21,4.7075,10.4,18.51,511.72
Credit,27.0,NaN,NaN,NaN,NaT,NaT,1153.084074,656.802133,7.83,648.84,1200.0,1602.72,2466.56

In [46]:
# Before we begin our Univariate Analysis, we must first search the dataset for any missing values, NaNs, and duplicate entries
print(combined.isnull().sum())   
print('\n')
print(combined.duplicated().sum())

Transaction Date       0
Posted Date            0
Card No.               0
Description            0
Category               0
Debit                 27
Credit              1948
dtype: int64


63